const DATASETS = [
  { id:'firstAid', label:'Prva pomoć', file:'data/prva-pomoc.json' },
  { id:'driverRules', label:'Saobraćaj - pravila i propisi', file:'data/saobracaj-pravila.json' },
  { id:'roadSigns', label:'Saobraćajni znakovi / Oblast II', file:'data/saobracajni-znakovi-oblast-ii.json' },
  { id:'situations', label:'Saobraćajne situacije / Oblast III', file:'data/saobracajne-situacije-oblast-iii.json' }
];
const STORAGE_KEY='neira_split_test_v1';
const el=id=>document.getElementById(id);
let banks={}, selectedCategoryId='firstAid', selectedCount=20, testQuestions=[], currentIndex=0, selectedAnswers={}, checkedAnswers={}, showAllReview=false;
const startPanel=el('startPanel'), testPanel=el('testPanel'), resultsPanel=el('resultsPanel'), categoryGrid=el('categoryGrid'), quickChoices=el('quickChoices'), customCount=el('customCount'), startBtn=el('startBtn'), resumeBox=el('resumeBox'), resumeBtn=el('resumeBtn'), discardSavedBtn=el('discardSavedBtn'), exitTestBtn=el('exitTestBtn'), questionNumber=el('questionNumber'), questionText=el('questionText'), questionImageWrap=el('questionImageWrap'), questionImage=el('questionImage'), multiNote=el('multiNote'), answersEl=el('answers'), feedbackBox=el('feedbackBox'), prevBtn=el('prevBtn'), nextBtn=el('nextBtn'), checkBtn=el('checkBtn'), finishBtn=el('finishBtn'), progressText=el('progressText'), progressFill=el('progressFill'), answeredBadge=el('answeredBadge'), activeTestLabel=el('activeTestLabel'), questionSelect=el('questionSelect'), scoreText=el('scoreText'), scoreSummary=el('scoreSummary'), review=el('review'), backToTestBtn=el('backToTestBtn'), resetBtn=el('resetBtn'), newRandomBtn=el('newRandomBtn'), toggleReviewBtn=el('toggleReviewBtn'), answerModal=el('answerModal'), modalHeader=el('modalHeader'), modalKicker=el('modalKicker'), modalTitle=el('modalTitle'), modalCorrectAnswer=el('modalCorrectAnswer'), modalMessage=el('modalMessage'), modalCloseBtn=el('modalCloseBtn'), modalCloseX=el('modalCloseX'), modalNextBtn=el('modalNextBtn');
function escapeHtml(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function clampCount(v){const n=Number(v);if(Number.isNaN(n))return 20;const max=banks[selectedCategoryId]?.length||100;return Math.max(1,Math.min(max,Math.floor(n)))}
function shuffle(a){const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c}
function normalize(ans){return [...(ans||[])].sort()}
function sameAnswer(a,b){a=normalize(a);b=normalize(b);return a.length===b.length&&a.every((x,i)=>x===b[i])}
function categoryLabel(id=selectedCategoryId){return DATASETS.find(d=>d.id===id)?.label||''}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify({selectedCategoryId,selectedCount,testQuestions,currentIndex,selectedAnswers,checkedAnswers}))}
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!s||!Array.isArray(s.testQuestions)||!s.testQuestions.length)return false;selectedCategoryId=s.selectedCategoryId||'firstAid';selectedCount=s.selectedCount||s.testQuestions.length;testQuestions=s.testQuestions;currentIndex=s.currentIndex||0;selectedAnswers=s.selectedAnswers||{};checkedAnswers=s.checkedAnswers||{};return true}catch{return false}}
function hasSavedTest(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));return Boolean(s&&Array.isArray(s.testQuestions)&&s.testQuestions.length)}catch{return false}}
function clearState(){localStorage.removeItem(STORAGE_KEY)}
function updateResumeBox(){resumeBox.classList.toggle('show',hasSavedTest())}
function showStartScreen(){startPanel.classList.remove('hidden');testPanel.classList.add('hidden');resultsPanel.style.display='none';answeredBadge.textContent=hasSavedTest()?'Sačuvan test u toku':'Nije započeto';updateResumeBox();renderCategories();window.scrollTo({top:0,behavior:'smooth'})}
function resumeSavedTest(){if(!loadState())return;startPanel.classList.add('hidden');testPanel.classList.remove('hidden');resultsPanel.style.display='none';populateSelect();renderQuestion();window.scrollTo({top:0,behavior:'smooth'})}
function renderCategories(){categoryGrid.innerHTML='';for(const d of DATASETS){const btn=document.createElement('button');btn.className='category-card'+(selectedCategoryId===d.id?' active':'');btn.dataset.id=d.id;btn.innerHTML=`<span class="category-title">${escapeHtml(d.label)}</span><span class="category-subtitle">${banks[d.id]?.length||0} pitanja</span>`;btn.addEventListener('click',()=>{selectedCategoryId=d.id;const max=banks[d.id].length;customCount.max=max;if(Number(customCount.value)>max)customCount.value=max;renderCategories()});categoryGrid.appendChild(btn)}}
function startNewTest(count){if(hasSavedTest()&&!confirm('Pokrenuti novi random test? Sačuvani test u toku će biti obrisan.'))return;selectedCount=clampCount(count);testQuestions=shuffle(banks[selectedCategoryId]).slice(0,selectedCount);currentIndex=0;selectedAnswers={};checkedAnswers={};showAllReview=false;saveState();startPanel.classList.add('hidden');testPanel.classList.remove('hidden');resultsPanel.style.display='none';populateSelect();renderQuestion();window.scrollTo({top:0,behavior:'smooth'})}
function selectedAnswerCount(){return testQuestions.filter(q=>(selectedAnswers[q.id]||[]).length).length}
function checkedAnswerCount(){return testQuestions.filter(q=>checkedAnswers[q.id]).length}
function populateSelect(){questionSelect.innerHTML='';testQuestions.forEach((q,i)=>{const opt=document.createElement('option');opt.value=i;opt.textContent=`Pitanje ${i+1}${(selectedAnswers[q.id]||[]).length?' ✓':''}${checkedAnswers[q.id]?' 🔍':''}`;questionSelect.appendChild(opt)})}
function updateProgress(){answeredBadge.textContent=`Odabrano: ${selectedAnswerCount()} / ${testQuestions.length} · Provjereno: ${checkedAnswerCount()} / ${testQuestions.length}`;progressFill.style.width=`${((currentIndex+1)/testQuestions.length)*100}%`}
function renderQuestion(){const q=testQuestions[currentIndex];if(!q)return;const selected=selectedAnswers[q.id]||[];const isChecked=Boolean(checkedAnswers[q.id]);const isMulti=q.correct.length>1;activeTestLabel.textContent=`${categoryLabel()} · ${testQuestions.length} pitanja`;questionNumber.textContent=`Pitanje ${currentIndex+1} od ${testQuestions.length} · Originalno #${q.number}${q.page?' · str. '+q.page:''}`;questionText.textContent=q.question;if(q.image){questionImage.src=q.image;questionImageWrap.classList.remove('hidden')}else{questionImage.removeAttribute('src');questionImageWrap.classList.add('hidden')}multiNote.classList.toggle('hidden',!isMulti);answersEl.innerHTML='';feedbackBox.className='feedback';feedbackBox.textContent='';for(const letter of Object.keys(q.options)){const label=document.createElement('label');label.className='answer';const input=document.createElement('input');input.type=isMulti?'checkbox':'radio';input.name=`question-${q.id}`;input.value=letter;input.checked=selected.includes(letter);input.disabled=isChecked;if(isChecked){label.classList.add('locked');if(q.correct.includes(letter))label.classList.add('reveal-correct');if(selected.includes(letter)&&q.correct.includes(letter))label.classList.add('checked-correct');if(selected.includes(letter)&&!q.correct.includes(letter))label.classList.add('checked-wrong')}input.addEventListener('change',()=>{let arr=selectedAnswers[q.id]?[...selectedAnswers[q.id]]:[];if(isMulti){if(input.checked&&!arr.includes(letter))arr.push(letter);if(!input.checked)arr=arr.filter(x=>x!==letter)}else{arr=[letter]}selectedAnswers[q.id]=normalize(arr);saveState();populateSelect();renderQuestion()});const letterSpan=document.createElement('span');letterSpan.className='letter';letterSpan.textContent=letter;const textSpan=document.createElement('span');textSpan.className='answer-text';textSpan.textContent=q.options[letter];label.append(input,letterSpan,textSpan);answersEl.appendChild(label)}if(isChecked){const ok=sameAnswer(selected,q.correct);const correctText=q.correct.map(l=>`${l} — ${q.options[l]}`).join(' | ');feedbackBox.className=`feedback ${ok?'good':'bad'}`;feedbackBox.innerHTML=`<strong>${ok?'Correct.':'Wrong.'}</strong> Tačan odgovor: ${escapeHtml(correctText)}`}checkBtn.classList.toggle('hidden',!selected.length||isChecked);prevBtn.disabled=currentIndex===0;nextBtn.classList.toggle('hidden',currentIndex===testQuestions.length-1);finishBtn.classList.toggle('hidden',currentIndex!==testQuestions.length-1);progressText.textContent=`Pitanje ${currentIndex+1} od ${testQuestions.length}`;questionSelect.value=currentIndex;updateProgress()}
function motivationalMessage(q,isCorrect){const text=`${q.question} ${Object.values(q.options).join(' ')}`.toLowerCase();const good=['Bravo Nekice!','Odlično, Neira!','Ma svaka čast, Nekice!','To je to, Neira!','Nekice, pogodak kao iz prve!'];const bad=['Nema veze, Nekice!','Polako, Neira!','Glavu gore, Nekice!','Skoro, Neira!','Nekice, ovo je samo vježba!'];let ending=isCorrect?'Ovo si riješila kao store manager u Nejra Beauty Hair salonu kad svi odjednom pitaju “Nekice, možeš li samo ovo?” — a ti već radiš tri stvari.':'Nije tačno, ali nema panike — i kad te u Nejra Beauty Hair salonu zovu dok radiš nešto drugo, ti prvo udahneš pa riješiš stvar redom.';if(/krvaren|rana|zavoj|opekot|disanj|kpr|reanim|šok|hitn|pomoć|puls|nesvjest/.test(text))ending=isCorrect?'Prva pomoć ide super; beba navija iz prvog reda, a salon može biti miran — Nekice ima situaciju pod kontrolom.':'Prva pomoć zna biti zeznuta, ali učiš mirno — kao kad u salonu istovremeno zvoni telefon, neko traži račun, a neko viče “Nekiceee!”.';else if(/znak|saobraćajni|putokaz|kolovoz|oznaka|semafor|svjetlo|raskrsnic|redoslijed|prolaska|propustiti|skretanja|situaciji/.test(text))ending=isCorrect?'Saobraćaj si pročitala odlično — kao kad u salonu jednim pogledom vidiš ko treba račun, ko čeka termin, a ko opet traži “samo malu uslugu”.':'Ove situacije vole male zamke, ali nema nervoze — Nekice se ne predaje ni kad je zovu baš u trenutku kad je zauzeta.';const pool=isCorrect?good:bad;return `${pool[Math.floor(Math.random()*pool.length)]} ${ending}`}
function showAnswerModal(q){const selected=selectedAnswers[q.id]||[];const ok=sameAnswer(selected,q.correct);const correctText=q.correct.map(l=>`<strong>${escapeHtml(l)}</strong> — ${escapeHtml(q.options[l])}`).join('<br>');modalHeader.className=`modal-header ${ok?'correct':'wrong'}`;modalKicker.textContent=`Pitanje ${currentIndex+1} od ${testQuestions.length}`;modalTitle.textContent=ok?'Correct! 🎉':'Wrong — but learning! 💪';modalCorrectAnswer.innerHTML=correctText;modalMessage.textContent=motivationalMessage(q,ok);modalNextBtn.textContent=currentIndex===testQuestions.length-1?'Finish test':'Next question';answerModal.classList.add('show');modalCloseBtn.focus()}
function closeAnswerModal(){answerModal.classList.remove('show')}
function goNextFromModal(){closeAnswerModal();if(currentIndex<testQuestions.length-1){currentIndex++;saveState();renderQuestion()}else finishTest()}
function checkCurrentAnswer(){const q=testQuestions[currentIndex];if(!(selectedAnswers[q.id]||[]).length)return;checkedAnswers[q.id]=true;saveState();populateSelect();renderQuestion();showAnswerModal(q)}
function finishTest(){const correct=testQuestions.filter(q=>sameAnswer(selectedAnswers[q.id]||[],q.correct)).length;const percentage=Math.round(correct/testQuestions.length*100);const unanswered=testQuestions.filter(q=>!(selectedAnswers[q.id]||[]).length).length;scoreText.textContent=`${correct} / ${testQuestions.length} (${percentage}%)`;scoreText.className=percentage>=80?'score good':'score bad';scoreSummary.textContent=unanswered?`${unanswered} pitanja nisu odgovorena. Neodgovorena pitanja se računaju kao netačna.`:'Odgovorila si na sva pitanja.';testPanel.classList.add('hidden');resultsPanel.style.display='block';renderReview();window.scrollTo({top:0,behavior:'smooth'})}
function renderReview(){review.innerHTML='';const items=testQuestions.filter(q=>showAllReview||!sameAnswer(selectedAnswers[q.id]||[],q.correct));if(!items.length){review.innerHTML="<div class='review-item correct'><div class='review-title'>Sve tačno 🎉</div><div class='small'>Nema netačnih odgovora.</div></div>";return}items.forEach(q=>{const selected=selectedAnswers[q.id]||[];const ok=sameAnswer(selected,q.correct);const div=document.createElement('div');div.className=`review-item ${ok?'correct':'wrong'}`;const userText=selected.length?selected.map(l=>`${l} — ${q.options[l]}`).join(' | '):'Nije odgovoreno';const correctText=q.correct.map(l=>`${l} — ${q.options[l]}`).join(' | ');div.innerHTML=`<div class="review-title">Originalno #${q.number}: ${escapeHtml(q.question)}</div><div class="small"><strong>Tvoj odgovor:</strong> ${escapeHtml(userText)}</div><div class="small"><strong>Tačan odgovor:</strong> ${escapeHtml(correctText)}</div>`;review.appendChild(div)})}
quickChoices.addEventListener('click',e=>{const b=e.target.closest('.choice-card');if(!b)return;document.querySelectorAll('.choice-card').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedCount=clampCount(b.dataset.count);customCount.value=selectedCount});customCount.addEventListener('input',()=>{selectedCount=clampCount(customCount.value);document.querySelectorAll('.choice-card').forEach(x=>x.classList.toggle('active',Number(x.dataset.count)===selectedCount))});startBtn.addEventListener('click',()=>startNewTest(customCount.value));checkBtn.addEventListener('click',checkCurrentAnswer);prevBtn.addEventListener('click',()=>{if(currentIndex>0){currentIndex--;saveState();renderQuestion()}});nextBtn.addEventListener('click',()=>{if(currentIndex<testQuestions.length-1){currentIndex++;saveState();renderQuestion()}});finishBtn.addEventListener('click',finishTest);questionSelect.addEventListener('change',e=>{currentIndex=Number(e.target.value);saveState();renderQuestion()});backToTestBtn.addEventListener('click',()=>{resultsPanel.style.display='none';testPanel.classList.remove('hidden');renderQuestion();window.scrollTo({top:0,behavior:'smooth'})});resetBtn.addEventListener('click',()=>{if(!confirm('Obrisati odgovore za ovaj test?'))return;selectedAnswers={};checkedAnswers={};currentIndex=0;showAllReview=false;saveState();resultsPanel.style.display='none';testPanel.classList.remove('hidden');populateSelect();renderQuestion()});newRandomBtn.addEventListener('click',()=>{if(!confirm('Pokrenuti novi random test? Trenutni odgovori će biti obrisani.'))return;clearState();showStartScreen()});toggleReviewBtn.addEventListener('click',()=>{showAllReview=!showAllReview;toggleReviewBtn.textContent=showAllReview?'Show only wrong/unanswered':'Show all';renderReview()});resumeBtn.addEventListener('click',resumeSavedTest);discardSavedBtn.addEventListener('click',()=>{if(!confirm('Obrisati sačuvani test?'))return;clearState();updateResumeBox();answeredBadge.textContent='Nije započeto'});exitTestBtn.addEventListener('click',()=>{saveState();if(!confirm('Izaći iz trenutnog testa? Napredak će ostati sačuvan.'))return;showStartScreen()});modalCloseBtn.addEventListener('click',closeAnswerModal);modalCloseX.addEventListener('click',closeAnswerModal);modalNextBtn.addEventListener('click',goNextFromModal);answerModal.addEventListener('click',e=>{if(e.target===answerModal)closeAnswerModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&answerModal.classList.contains('show'))closeAnswerModal()});
(async function init(){try{for(const d of DATASETS){const res=await fetch(d.file);if(!res.ok)throw new Error(d.file);banks[d.id]=await res.json()}renderCategories();updateResumeBox();answeredBadge.textContent=hasSavedTest()?'Sačuvan test u toku':'Nije započeto'}catch(err){startPanel.innerHTML='<h2>Greška pri učitavanju podataka</h2><p>Ovaj split projekat treba otvoriti preko GitHub Pages ili lokalnog servera, ne direktno kao file://.</p><p class="small">Detalj: '+escapeHtml(err.message)+'</p>'}})();
